project:
  type: website
  output-dir: docs

website:
  title: "F1Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Local Stats.qmd
        text: Local stats
      - Animated D3 Graphs.qmd
      - OJS and D3.qmd
      - Scrolling Constructrs Season.qmd
      
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

